const jobData = [
    {
        name: "Full Stack Development",
        company: "XYZ",
        description: "We need ever thoughtful problem-solving engineer",
        date: "Immediate",
        mode: "Remote",
        stipend: "1000/month",
        duration: "3 months",
    },
    {
        name: "Full Stack Development",
        company: "XYZ",
        description: "We need ever thoughtful problem-solving engineer",
        date: "Immediate",
        mode: "Remote",
        stipend: "1000/month",
        duration: "3 months",
    },
    {
        name: "Full Stack Development",
        company: "XYZ",
        description: "We need ever thoughtful problem-solving engineer",
        date: "Immediate",
        mode: "Remote",
        stipend: "1000/month",
        duration: "3 months",
    },
    {
        name: "Full Stack Development",
        company: "XYZ",
        description: "We need ever thoughtful problem-solving engineer",
        date: "Immediate",
        mode: "Remote",
        stipend: "1000/month",
        duration: "3 months",
    },
    {
        name: "Full Stack Development",
        company: "XYZ",
        description: "We need ever thoughtful problem-solving engineer",
        date: "Immediate",
        mode: "Remote",
        stipend: "1000/month",
        duration: "3 months",
    },
    {
        name: "Full Stack Development",
        company: "XYZ",
        description: "We need ever thoughtful problem-solving engineer",
        date: "Immediate",
        mode: "Remote",
        stipend: "1000/month",
        duration: "3 months",
    },
    {
        name: "Full Stack Development",
        company: "XYZ",
        description: "We need ever thoughtful problem-solving engineer",
        date: "Immediate",
        mode: "Remote",
        stipend: "1000/month",
        duration: "3 months",
    }
]

export default jobData;